included:
  - SukkarApp

excluded:
  - Pods
disabled_rules:
  - file_types_order
  - force_unwrapping
  - vertical_whitespace_between_cases
  - trailing_whitespace
  - unneeded_override
  - colon
  - mark
  - comment_spacing
  - opening_brace
  - force_cast
  - line_length
  - force_try
  - vertical_whitespace
  - comma
  - trailing_newline
  - identifier_name
  - function_parameter_count
  - unused_closure_parameter
  - type_body_length
  - implicit_getter
  - cyclomatic_complexity
  - legacy_constructor
  - control_statement
  - type_name
  - file_length
  - nesting
  - empty_enum_arguments
  - redundant_string_enum_value
  - unused_setter_value
  - blanket_disable_command
  - legacy_random
  - operator_whitespace
  - statement_position
  - redundant_optional_initialization
  - function_body_length
  - unused_enumerated
  - notification_center_detachment
  - trailing_semicolon
  - computed_accessors_order
  - no_space_in_method_call
  - closing_brace
  - switch_case_alignment
  - return_arrow_whitespace
  - unneeded_break_in_switch
  - discouraged_direct_init




